#!/bin/bash

g++ -c ImageTool/Code/ImageTool.cpp                                                 \
-I ImageTool/Headers/                                                               \
-std=c++17 -O3 -Wall -Wextra -L/usr/lib -ljpeg -lGL -lGLU -lglut -std=c++17         \

